travis:
  secure:
    BINSTAR_TOKEN: opSvWIGrvYCAcYBa+vfBudczAtJ06p4wTlKcMxRS46hocuSdVA3tIF5mrd1AqJhutZUe9nBvAsakht1cJyxhULru2qEULngnzCYA6GQK3FwaqN4yVLFPq2YlTTB4t2qMBe/bMNqM90mh3GtmUvvnmysTNfbpqifRGE0KHxzy76Ld5xqoBDWcMwlpWV2Zwe7fubvaJSTU/Pw0p8cK4l+f+9t8X9NFaUMaUtbidEdOQLUQgQu6nADIHd3i2EAKseP+SfwbGsh/PhdyTpl1waA1eae8S7yTn0q1qLDSbZbLbMeRgg6B0lcz+tMuYUfsJSPwSoqh9vi9GVlo1AFHu7JAaxA2Ajtu5wKnBc379/QdViocvl+bq4IrmVjlBxXj5H+3YJdMphXlMw+uL7GhZDD97qnLPbNzgOwpHeocsJ1dl0j15Ptn1MyReuKA5f7t4vJea58JA4KbVlFSBS8ej0Dt2sDlFfAy9R3KPvn5mJmmCf2qIq6ac33arJF2CQHI7KVaByMM+mNxOHew3EtbQ23/QKAoVosKlxA6mtMvXLQabkNDJ2uFVX4CI4E4m8pgZV2Z1IbLTE9RJe+24K5rdln+vaEHAhyQkLlrRWs+lFTzR9MrbmKErkUWEI/1+/skF90x0hgS/yAZZ8/9oFqa0qRTf9MOKnOY6PB06DTai6rR8Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
