travis:
  secure:
    BINSTAR_TOKEN: drNB21fXd9GP8dUc3+BCDIaPpO6LU2qaOhVByk/fp20cuA1UmocPR2J2w/kfn1G8ZPmIt9DvYvJz3GSSwzqsN29IIQUEOQuSE2SrMsq3yU6rLyA30mxphgHLuzL1MwH6EGnAmmxES11PAYN6ReWHvSvsL8i0iVRQSBzGQ1wg4PF6FHleCGEM/IPXiWc6tT05XXstLVPqXde5MKdFgAXC4znRDGPqew5fSkPOagJ2kttJQpFCnoLH1nlSvm6IAf1XQxYluLD49+SNLMBGHatiTXzUZslokDvCaKp9eWx+6+VjcDYzHIkCgKYooxutz1n9kiuOHwkBe0cocxyNR9dM7mkcYKUgqFOXNETE4vI/7O0Z5rbvo1wqn1sCcfHLnJ9tBII/xcEh2mmwRlWTF0zurLB5d6bZn0tD9nwfSIUKXah45Kpf/7mE6QBn+JfgqI431unUX/3IouWX9US6HCCrOF/3QcJ7Gp/+xyVjrImdxBVJiJW6UO7IZENxy+dxHcNjETy69tTAhtQvv81/9f5x/0R1xXN8aK6rta3qAZxbeu2CtY2eUrRa35oN9ugD+c+wiHARFwAeNTe1BEF2HScEwNT98mcOqs2SVnrpr9lP8RKFTqD1en4v3Hn4yA0H3C2hV6hF2p88x5wJjPA3Q8pP96BdDdYF5nmmaWozvhSnHXo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
