travis:
  secure:
    BINSTAR_TOKEN: PAIzJwr+/DpFR6iExTD++MM5esqJaiu3I17oeTkTRIYEkSmb6NFjYPRfYNXCbyCCgivb3ecdeciAQvDJeWH78fm8aDX9osjEBaa4uFZLVf5P5bDo3gDNJiI653rtmSd4TPXeU2zD7OobysEsDieUsfUrm3XW9jaWqjzJM/t0em+hQp7cLjUAm4WnfXYxPhuR/JsUFO2aHqjQG2siAFpVisCDHIbXK20VbzWxcgsb/p/jyifwqwpnB845A+Cg+NspiCBGsvBUySQEBEtb4Px4Dinp+2CpC6o284vv1VatjpjvVp4QVwT/Ws11mVUMLbSQKDr5RV7JyvReW/6bewN4xTTVPBUHA9TGI6ef5lF/mu0fuZ42DW5lryYwXb1BtL8LF6SPD7gAFkT0gEnHZR/4rpDaC/+wrWGr5q1PDINdWMKWgZP5x/e+LL98iVV50b7M5dquF2Who5NoXgDacpxmV8cXeTUEpuRDnSjU2J6dmHm14Co+3i6fAOevw9q94ZvKOoEwvmTPqBi5oQbo4Mc4ZeGxgGYh1Ds3Vt6rIT+V6H00RIFGFdDaBtXA3kcm/3YXJWpP/N7roWIqVDdQvL+tW4FhyQiyKh6NPcdzRp3JrDTZFvIlOpVM4N4E9ap+7kvHkV4gYn63EeQ0/+JarCNGHZwdoH57PiwlrrM8806Fo+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
